# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c573333a24522f832ba2893be7e2ea3a3ced7a01b6b9bc675ce506bbf212a34ab8831828b9f89c565e4e29e9c56ecca48eaf798ed528f087b7f8a45497e516

test:
  secret_key_base: 09b106aa7d926e268d7fb86d3969415c166af9e5769937d417ecd7e483bcbe20a8985aeaeba23975a9dbf82cd827060ac8ecc3593ca891956db29f996222116d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
